### ISSUE TITLE
Building docker images fails

### ISSUE THREAD

**Issue by brainplot** [valasek/timesheet#35]
**Describe the bug**
The image fails to build under Docker.

**To Reproduce**
After cloning the repo,
```bash
cd dockerfiles/cloud
docker build -t test .
```

**Expected behavior**
Code to build successfully.

**Output**
```
------
> [frontend 6/9] RUN yarn install:
#37 0.748 yarn install v1.22.15
#37 0.879 [1/5] Validating package.json...
#37 0.884 [2/5] Resolving packages...
#37 1.775 [3/5] Fetching packages...
#37 82.18 info fsevents@2.1.2: The platform "linux" is incompatible with this module.
#37 82.19 info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#37 82.20 info fsevents@1.2.9: The platform "linux" is incompatible with this module.
#37 82.20 info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
#37 82.23 [4/5] Linking dependencies...
#37 82.24 warning "@quasar/quasar-app-extension-qmarkdown > raw-loader@4.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#37 82.25 warning " > eslint-loader@3.0.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#37 113.4 [5/5] Building fresh packages...
#37 118.2 error /client/node_modules/node-sass: Command failed.
#37 118.2 Exit code: 1
#37 118.2 Command: node scripts/build.js
#37 118.2 Arguments:
#37 118.2 Directory: /client/node_modules/node-sass
#37 118.2 Output:
#37 118.2 Building: /usr/local/bin/node /client/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#37 118.2 gyp info it worked if it ends with ok
#37 118.2 gyp verb cli [
#37 118.2 gyp verb cli '/usr/local/bin/node',
#37 118.2 gyp verb cli '/client/node_modules/node-gyp/bin/node-gyp.js',
#37 118.2 gyp verb cli 'rebuild',
#37 118.2 gyp verb cli '--verbose',
#37 118.2 gyp verb cli '--libsass_ext=',
#37 118.2 gyp verb cli '--libsass_cflags=',
#37 118.2 gyp verb cli '--libsass_ldflags=',
#37 118.2 gyp verb cli '--libsass_library='
#37 118.2 gyp verb cli ]
#37 118.2 gyp info using node-gyp@3.8.0
#37 118.2 gyp info using node@14.18.1 | linux | x64
#37 118.2 gyp verb command rebuild []
#37 118.2 gyp verb command clean []
#37 118.2 gyp verb clean removing "build" directory
#37 118.2 gyp verb command configure []
#37 118.2 gyp verb check python checking for Python executable "python2" in the PATH
#37 118.2 gyp verb `which` failed Error: not found: python2
#37 118.2 gyp verb `which` failed at getNotFoundError (/client/node_modules/which/which.js:13:12)
#37 118.2 gyp verb `which` failed at F (/client/node_modules/which/which.js:68:19)
#37 118.2 gyp verb `which` failed at E (/client/node_modules/which/which.js:80:29)
#37 118.2 gyp verb `which` failed at /client/node_modules/which/which.js:89:16
#37 118.2 gyp verb `which` failed at /client/node_modules/isexe/index.js:42:5
#37 118.2 gyp verb `which` failed at /client/node_modules/isexe/mode.js:8:5
#37 118.2 gyp verb `which` failed at FSReqCallback.oncomplete (fs.js:191:21)
#37 118.2 gyp verb `which` failed python2 Error: not found: python2
#37 118.2 gyp verb `which` failed at getNotFoundError (/client/node_modules/which/which.js:13:12)
#37 118.2 gyp verb `which` failed at F (/client/node_modules/which/which.js:68:19)
#37 118.2 gyp verb `which` failed at E (/client/node_modules/which/which.js:80:29)
#37 118.2 gyp verb `which` failed at /client/node_modules/which/which.js:89:16
#37 118.2 gyp verb `which` failed at /client/node_modules/isexe/index.js:42:5
#37 118.2 gyp verb `which` failed at /client/node_modules/isexe/mode.js:8:5
#37 118.2 gyp verb `which` failed at FSReqCallback.oncomplete (fs.js:191:21) {
#37 118.2 gyp verb `which` failed code: 'ENOENT'
#37 118.2 gyp verb `which` failed }
#37 118.2 gyp verb check python checking for Python executable "python" in the PATH
#37 118.2 gyp verb `which` failed Error: not found: python
#37 118.2 gyp verb `which` failed at getNotFoundError (/client/node_modules/which/which.js:13:12)
#37 118.2 gyp verb `which` failed at F (/client/node_modules/which/which.js:68:19)
#37 118.2 gyp verb `which` failed at E (/client/node_modules/which/which.js:80:29)
#37 118.2 gyp verb `which` failed at /client/node_modules/which/which.js:89:16
#37 118.2 gyp verb `which` failed at /client/node_modules/isexe/index.js:42:5
#37 118.2 gyp verb `which` failed at /client/node_modules/isexe/mode.js:8:5
#37 118.2 gyp verb `which` failed at FSReqCallback.oncomplete (fs.js:191:21)
#37 118.2 gyp verb `which` failed python Error: not found: python
#37 118.2 gyp verb `which` failed at getNotFoundError (/client/node_modules/which/which.js:13:12)
#37 118.2 gyp verb `which` failed at F (/client/node_modules/which/which.js:68:19)
#37 118.2 gyp verb `which` failed at E (/client/node_modules/which/which.js:80:29)
#37 118.2 gyp verb `which` failed at /client/node_modules/which/which.js:89:16
#37 118.2 gyp verb `which` failed at /client/node_modules/isexe/index.js:42:5
#37 118.2 gyp verb `which` failed at /client/node_modules/isexe/mode.js:8:5
#37 118.2 gyp verb `which` failed at FSReqCallback.oncomplete (fs.js:191:21) {
#37 118.2 gyp verb `which` failed code: 'ENOENT'
#37 118.2 gyp verb `which` failed }
#37 118.2 gyp ERR! configure error
#37 118.2 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#37 118.2 gyp ERR! stack at PythonFinder.failNoPython (/client/node_modules/node-gyp/lib/configure.js:484:19)
#37 118.2 gyp ERR! stack at PythonFinder.<anonymous> (/client/node_modules/node-gyp/lib/configure.js:406:16)
#37 118.2 gyp ERR! stack at F (/client/node_modules/which/which.js:68:16)
#37 118.2 gyp ERR! stack at E (/client/node_modules/which/which.js:80:29)
#37 118.2 gyp ERR! stack at /client/node_modules/which/which.js:89:16
#37 118.2 gyp ERR! stack at /client/node_modules/isexe/index.js:42:5
#37 118.2 gyp ERR! stack at /client/node_modules/isexe/mode.js:8:5
#37 118.2 gyp ERR! stack at FSReqCallback.oncomplete (fs.js:191:21)
#37 118.2 gyp ERR! System Linux 5.10.47-linuxkit
#37 118.2 gyp ERR! command "/usr/local/bin/node" "/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#37 118.2 gyp ERR! cwd /client/node_modules/node-sass
#37 118.2 gyp ERR! node -v v14.18.1
#37 118.2 gyp ERR! node-gyp -v v3.8.0
#37 118.2 gyp ERR! not ok
#37 118.2 Build failed with error code: 1
#37 118.2 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install]: exit code: 1
```

**Desktop:**
 - OS: MacOS 11.6

**Docker Version:**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:53:34 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by noraj** [comment]
I have been trying the dev flavor of the docker-compose template

```
docker-compose -f docker-compose-dev.yml up -d --build
```

but it fails 

![image](https://user-images.githubusercontent.com/16578570/177171791-f905eda5-0e9e-4d8f-87d3-a0a45a65779c.png)

```
 > [frontend 6/9] RUN yarn install:
#0 0.410 yarn install v1.22.19
#0 0.471 [1/5] Validating package.json...
#0 0.474 [2/5] Resolving packages...
#0 0.898 [3/5] Fetching packages...
#0 50.69 [4/5] Linking dependencies...
#0 50.72 warning "@quasar/quasar-app-extension-qmarkdown > raw-loader@4.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#0 50.72 warning " > eslint-loader@3.0.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#0 65.37 [5/5] Building fresh packages...
#0 67.80 error /client/node_modules/node-sass: Command failed.
#0 67.80 Exit code: 1
#0 67.80 Command: node scripts/build.js
#0 67.80 Arguments:
#0 67.80 Directory: /client/node_modules/node-sass
#0 67.80 Output:
#0 67.80 Building: /usr/local/bin/node /client/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#0 67.80 gyp info it worked if it ends with ok
#0 67.80 gyp verb cli [
#0 67.80 gyp verb cli   '/usr/local/bin/node',
#0 67.80 gyp verb cli   '/client/node_modules/node-gyp/bin/node-gyp.js',
#0 67.80 gyp verb cli   'rebuild',
#0 67.80 gyp verb cli   '--verbose',
#0 67.80 gyp verb cli   '--libsass_ext=',
#0 67.80 gyp verb cli   '--libsass_cflags=',
#0 67.80 gyp verb cli   '--libsass_ldflags=',
#0 67.80 gyp verb cli   '--libsass_library='
#0 67.80 gyp verb cli ]
#0 67.80 gyp info using node-gyp@3.8.0
#0 67.80 gyp info using node@16.15.1 | linux | x64
#0 67.80 gyp verb command rebuild []
#0 67.80 gyp verb command clean []
#0 67.80 gyp verb clean removing "build" directory
#0 67.80 gyp verb command configure []
#0 67.80 gyp verb check python checking for Python executable "python2" in the PATH
#0 67.80 gyp verb `which` failed Error: not found: python2
#0 67.80 gyp verb `which` failed     at getNotFoundError (/client/node_modules/which/which.js:13:12)
#0 67.80 gyp verb `which` failed     at F (/client/node_modules/which/which.js:68:19)
#0 67.80 gyp verb `which` failed     at E (/client/node_modules/which/which.js:80:29)
#0 67.80 gyp verb `which` failed     at /client/node_modules/which/which.js:89:16
#0 67.80 gyp verb `which` failed     at /client/node_modules/isexe/index.js:42:5
#0 67.80 gyp verb `which` failed     at /client/node_modules/isexe/mode.js:8:5
#0 67.80 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
#0 67.80 gyp verb `which` failed  python2 Error: not found: python2
#0 67.80 gyp verb `which` failed     at getNotFoundError (/client/node_modules/which/which.js:13:12)
#0 67.80 gyp verb `which` failed     at F (/client/node_modules/which/which.js:68:19)
#0 67.80 gyp verb `which` failed     at E (/client/node_modules/which/which.js:80:29)
#0 67.80 gyp verb `which` failed     at /client/node_modules/which/which.js:89:16
#0 67.80 gyp verb `which` failed     at /client/node_modules/isexe/index.js:42:5
#0 67.80 gyp verb `which` failed     at /client/node_modules/isexe/mode.js:8:5
#0 67.80 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
#0 67.80 gyp verb `which` failed   code: 'ENOENT'
#0 67.80 gyp verb `which` failed }
#0 67.80 gyp verb check python checking for Python executable "python" in the PATH
#0 67.80 gyp verb `which` failed Error: not found: python
#0 67.80 gyp verb `which` failed     at getNotFoundError (/client/node_modules/which/which.js:13:12)
#0 67.80 gyp verb `which` failed     at F (/client/node_modules/which/which.js:68:19)
#0 67.80 gyp verb `which` failed     at E (/client/node_modules/which/which.js:80:29)
#0 67.80 gyp verb `which` failed     at /client/node_modules/which/which.js:89:16
#0 67.80 gyp verb `which` failed     at /client/node_modules/isexe/index.js:42:5
#0 67.80 gyp verb `which` failed     at /client/node_modules/isexe/mode.js:8:5
#0 67.80 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
#0 67.80 gyp verb `which` failed  python Error: not found: python
#0 67.80 gyp verb `which` failed     at getNotFoundError (/client/node_modules/which/which.js:13:12)
#0 67.80 gyp verb `which` failed     at F (/client/node_modules/which/which.js:68:19)
#0 67.80 gyp verb `which` failed     at E (/client/node_modules/which/which.js:80:29)
#0 67.80 gyp verb `which` failed     at /client/node_modules/which/which.js:89:16
#0 67.80 gyp verb `which` failed     at /client/node_modules/isexe/index.js:42:5
#0 67.80 gyp verb `which` failed     at /client/node_modules/isexe/mode.js:8:5
#0 67.80 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
#0 67.80 gyp verb `which` failed   code: 'ENOENT'
#0 67.80 gyp verb `which` failed }
#0 67.80 gyp ERR! configure error
#0 67.80 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#0 67.80 gyp ERR! stack     at PythonFinder.failNoPython (/client/node_modules/node-gyp/lib/configure.js:484:19)
#0 67.80 gyp ERR! stack     at PythonFinder.<anonymous> (/client/node_modules/node-gyp/lib/configure.js:406:16)
#0 67.80 gyp ERR! stack     at F (/client/node_modules/which/which.js:68:16)
#0 67.80 gyp ERR! stack     at E (/client/node_modules/which/which.js:80:29)
#0 67.80 gyp ERR! stack     at /client/node_modules/which/which.js:89:16
#0 67.80 gyp ERR! stack     at /client/node_modules/isexe/index.js:42:5
#0 67.80 gyp ERR! stack     at /client/node_modules/isexe/mode.js:8:5
#0 67.80 gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
#0 67.80 gyp ERR! System Linux 5.18.9-arch1-1
#0 67.80 gyp ERR! command "/usr/local/bin/node" "/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#0 67.80 gyp ERR! cwd /client/node_modules/node-sass
#0 67.80 gyp ERR! node -v v16.15.1
#0 67.80 gyp ERR! node-gyp -v v3.8.0
#0 67.80 gyp ERR! not ok
#0 67.80 Build failed with error code: 1
#0 67.80 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn install]: exit code: 1
```

Then I wanted to try the dataarch flavor since they have different yarn build steps and it is what failed previously.

![image](https://user-images.githubusercontent.com/16578570/177172143-5e6cf412-15f4-4bf5-9af2-2675bfdff3cd.png)

```
docker-compose -f docker-compose-dataarch.yml up -d --build
```

But it fails too

![image](https://user-images.githubusercontent.com/16578570/177172235-124d0513-e009-474c-88ab-cade9e1d76f3.png)

```
 > [frontend  6/10] RUN yarn install:
#0 0.393 yarn install v1.22.19
#0 0.467 [1/5] Validating package.json...
#0 0.469 [2/5] Resolving packages...
#0 1.047 [3/5] Fetching packages...
#0 43.80 [4/5] Linking dependencies...
#0 43.81 warning "@quasar/quasar-app-extension-qmarkdown > raw-loader@4.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#0 43.81 warning " > eslint-loader@3.0.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#0 54.23 [5/5] Building fresh packages...
#0 56.24 error /client/node_modules/node-sass: Command failed.
#0 56.24 Exit code: 1
#0 56.24 Command: node scripts/build.js
#0 56.24 Arguments:
#0 56.24 Directory: /client/node_modules/node-sass
#0 56.24 Output:
#0 56.24 Building: /usr/local/bin/node /client/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#0 56.24 gyp info it worked if it ends with ok
#0 56.24 gyp verb cli [
#0 56.24 gyp verb cli   '/usr/local/bin/node',
#0 56.24 gyp verb cli   '/client/node_modules/node-gyp/bin/node-gyp.js',
#0 56.24 gyp verb cli   'rebuild',
#0 56.24 gyp verb cli   '--verbose',
#0 56.24 gyp verb cli   '--libsass_ext=',
#0 56.24 gyp verb cli   '--libsass_cflags=',
#0 56.24 gyp verb cli   '--libsass_ldflags=',
#0 56.24 gyp verb cli   '--libsass_library='
#0 56.24 gyp verb cli ]
#0 56.24 gyp info using node-gyp@3.8.0
#0 56.24 gyp info using node@16.15.1 | linux | x64
#0 56.24 gyp verb command rebuild []
#0 56.24 gyp verb command clean []
#0 56.24 gyp verb clean removing "build" directory
#0 56.24 gyp verb command configure []
#0 56.24 gyp verb check python checking for Python executable "python2" in the PATH
#0 56.24 gyp verb `which` failed Error: not found: python2
#0 56.24 gyp verb `which` failed     at getNotFoundError (/client/node_modules/which/which.js:13:12)
#0 56.24 gyp verb `which` failed     at F (/client/node_modules/which/which.js:68:19)
#0 56.24 gyp verb `which` failed     at E (/client/node_modules/which/which.js:80:29)
#0 56.24 gyp verb `which` failed     at /client/node_modules/which/which.js:89:16
#0 56.24 gyp verb `which` failed     at /client/node_modules/isexe/index.js:42:5
#0 56.24 gyp verb `which` failed     at /client/node_modules/isexe/mode.js:8:5
#0 56.24 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
#0 56.24 gyp verb `which` failed  python2 Error: not found: python2
#0 56.24 gyp verb `which` failed     at getNotFoundError (/client/node_modules/which/which.js:13:12)
#0 56.24 gyp verb `which` failed     at F (/client/node_modules/which/which.js:68:19)
#0 56.24 gyp verb `which` failed     at E (/client/node_modules/which/which.js:80:29)
#0 56.24 gyp verb `which` failed     at /client/node_modules/which/which.js:89:16
#0 56.24 gyp verb `which` failed     at /client/node_modules/isexe/index.js:42:5
#0 56.24 gyp verb `which` failed     at /client/node_modules/isexe/mode.js:8:5
#0 56.24 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
#0 56.24 gyp verb `which` failed   code: 'ENOENT'
#0 56.24 gyp verb `which` failed }
#0 56.24 gyp verb check python checking for Python executable "python" in the PATH
#0 56.24 gyp verb `which` failed Error: not found: python
#0 56.24 gyp verb `which` failed     at getNotFoundError (/client/node_modules/which/which.js:13:12)
#0 56.24 gyp verb `which` failed     at F (/client/node_modules/which/which.js:68:19)
#0 56.24 gyp verb `which` failed     at E (/client/node_modules/which/which.js:80:29)
#0 56.24 gyp verb `which` failed     at /client/node_modules/which/which.js:89:16
#0 56.24 gyp verb `which` failed     at /client/node_modules/isexe/index.js:42:5
#0 56.24 gyp verb `which` failed     at /client/node_modules/isexe/mode.js:8:5
#0 56.24 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
#0 56.24 gyp verb `which` failed  python Error: not found: python
#0 56.24 gyp verb `which` failed     at getNotFoundError (/client/node_modules/which/which.js:13:12)
#0 56.24 gyp verb `which` failed     at F (/client/node_modules/which/which.js:68:19)
#0 56.24 gyp verb `which` failed     at E (/client/node_modules/which/which.js:80:29)
#0 56.24 gyp verb `which` failed     at /client/node_modules/which/which.js:89:16
#0 56.24 gyp verb `which` failed     at /client/node_modules/isexe/index.js:42:5
#0 56.24 gyp verb `which` failed     at /client/node_modules/isexe/mode.js:8:5
#0 56.24 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
#0 56.24 gyp verb `which` failed   code: 'ENOENT'
#0 56.24 gyp verb `which` failed }
#0 56.24 gyp ERR! configure error
#0 56.24 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#0 56.24 gyp ERR! stack     at PythonFinder.failNoPython (/client/node_modules/node-gyp/lib/configure.js:484:19)
#0 56.24 gyp ERR! stack     at PythonFinder.<anonymous> (/client/node_modules/node-gyp/lib/configure.js:406:16)
#0 56.24 gyp ERR! stack     at F (/client/node_modules/which/which.js:68:16)
#0 56.24 gyp ERR! stack     at E (/client/node_modules/which/which.js:80:29)
#0 56.24 gyp ERR! stack     at /client/node_modules/which/which.js:89:16
#0 56.24 gyp ERR! stack     at /client/node_modules/isexe/index.js:42:5
#0 56.24 gyp ERR! stack     at /client/node_modules/isexe/mode.js:8:5
#0 56.24 gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
#0 56.24 gyp ERR! System Linux 5.18.9-arch1-1
#0 56.24 gyp ERR! command "/usr/local/bin/node" "/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#0 56.24 gyp ERR! cwd /client/node_modules/node-sass
#0 56.24 gyp ERR! node -v v16.15.1
#0 56.24 gyp ERR! node-gyp -v v3.8.0
#0 56.24 gyp ERR! not ok
#0 56.24 Build failed with error code: 1
#0 56.24 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn install]: exit code: 1
```

I didn't tried the cloud flavor, but I guess it will result in the same way.

I'm not surprised it's going wrong since there is not fixed version for docker images `image: postgres` and `FROM golang:alpine AS backend`. So as the project is abandoned nobody have made the change for it to work with new versions of alpine, go and postgresql and to update the JS dependencies.

**Comment by jonobailey** [comment]
@brainplot Move the dockerfile to the root of the project and build.
